### ISSUE TITLE
fix: exception when trying to resume a cancelled download

### ISSUE THREAD

**Issue by sgettys** [defenseunicorns/koci#29]
Interrupted a download and tried to resume but code kept crashing with this exception:
```
FATAL EXCEPTION: main
Process: com.defenseunicorns.uds, PID: 6445
com.defenseunicorns.koci.OCIException$SizeMismatch: Size mismatch: expected (70873) got (283492)
	at com.defenseunicorns.koci.Layout$push$2.invokeSuspend(Layout.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9c2664c, Dispatchers.Main.immediate]
```

Added in cleanup to push to delete the offending blob and this fixed the issue but I would expect that this would be handled by the guard for checking if the blob exists in the pull method:

```
when (val exception = ok.exceptionOrNull()) {
                is OCIException.SizeMismatch -> {
                    if (supportsRange(descriptor)) {
                        val start = exception.actual

                        // fire partial progress has happened
                        send(start.toInt())

                        headers.append("Range", "bytes=$start-${descriptor.size - 1}")
                    } else {
                        store.remove(descriptor).getOrThrow()
                    }
                }
```

This only happened a single time and could not get to repeat but once it was in this state the corrupted package was unable to be downloaded

**Comment by Noxsios** [comment]
@sgettys is it ok if I close this?

Current unit tests should be catching this edge case.
